### ISSUE TITLE
HTML comment inside of the javascript file

### ISSUE THREAD

**Issue by gabrielperales** [FAC9/repos_api_website#37]
I've seen this https://github.com/FAC9/repos_api_website/blob/master/js/app.js#L98 
Is that working? I think it will break your code, won't it?

**Comment by SavageWilliam** [comment]
the parseMovieDetails() function is a regular synchronous function right? I believe it updates our object defined at the top within the function getMovieDetails() which is called in the waterfall.

Seems to work :D

**Comment by gabrielperales** [comment]
Oh!, I was talking about this https://github.com/FAC9/repos_api_website/blob/master/js/app.js#L108 not the other line! 
Your are writing a html comment `<!-- ...... -->` inside a javascript file.... it shouldn't work.

**Comment by shiryz** [comment]
It's line 182 now , I think it works this way too :| , weird!
