### ISSUE TITLE
Top Right + Button does not open modal when gifs generates

### ISSUE THREAD

**Issue by njsfield** [FAC9/repos_api_website#66]
+ button works on home, but after gifs generated it doesn't function. 

Issue is that when gifs are generated, the section with id="page1" (that contains this modal element) is set to "display: none", which means that the button is functioning but the modal is inside a section with "display: none". Perhaps move the modal out of that container and elsewhere in the document

**Comment by RhodesPeter** [comment]
Thank you Nick! Team Repos, I got this one.
