### ISSUE TITLE
Giphy - get random movie GIF

### ISSUE THREAD

**Issue by emilyb7** [FAC9/repos_api_website#8]
Get a random gif. The search query should be the name of the movie and the word movie, e.g "Frozen movie"

Giphys come in all different sizes. How will we handle these on our app?

Our app needs to be mobile first and therefore data is an issue. Can we possibly compress / minify our GIFs in the front end?

**Comment by SavageWilliam** [comment]
the giphy api provides  a giph with fixed height!
